language: python
python:
  - "3.6"

matrix:
  include:
    - os: linux
    - os: osx

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pytest -v -n 2 --durations=10
